-- Create user_bookmarks table for tracking bookmarked notes
CREATE TABLE IF NOT EXISTS public.user_bookmarks (
    id bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    user_id uuid NOT NULL,
    note_id uuid NOT NULL,
    bookmarked_at timestamp without time zone DEFAULT now(),
    created_at timestamp without time zone DEFAULT now(),
    UNIQUE(user_id, note_id),
    CONSTRAINT fk_user_bookmarks_user_id FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE,
    CONSTRAINT fk_user_bookmarks_note_id FOREIGN KEY (note_id) REFERENCES public.notes(id) ON DELETE CASCADE
);

-- Create indexes for better query performance
CREATE INDEX IF NOT EXISTS idx_user_bookmarks_user_id ON public.user_bookmarks(user_id);
CREATE INDEX IF NOT EXISTS idx_user_bookmarks_note_id ON public.user_bookmarks(note_id);
CREATE INDEX IF NOT EXISTS idx_user_bookmarks_bookmarked_at ON public.user_bookmarks(bookmarked_at);
